use std::{fs,path::Path};
use terri_core::{SaveSnapshotV5,SimCommand};
use terri_wasm::SimHandle;
fn state(h:&SimHandle)->SaveSnapshotV5{postcard::from_bytes(&h.save_bytes()[10..]).unwrap()}
fn send(h:&mut SimHandle,c:SimCommand){assert!(h.enqueue_command(&postcard::to_allocvec(&c).unwrap()));}
fn object(s:&SaveSnapshotV5,id:&str)->u32{s.world.entities.iter().find(|e|e.smart_object.as_deref()==Some(id)).unwrap().index}
fn people(s:&SaveSnapshotV5)->Vec<u32>{s.world.entities.iter().filter(|e|e.agent).map(|e|e.index).collect()}
fn feel(s:&SaveSnapshotV5,a:u32,b:u32)->f32{let id=s.world.entities.iter().find(|e|e.index==b).unwrap().sim_id.unwrap();s.world.entities.iter().find(|e|e.index==a).unwrap().relationships.as_ref().and_then(|r|r.iter().find(|(p,_)|*p==id)).map_or(0.,|(_,f)|*f)}
fn capture(root:&Path,name:&str,h:&mut SimHandle){let bytes=h.save_bytes();let s=state(h);fs::write(root.join(format!("{name}.bin")),&bytes).unwrap();fs::write(root.join(format!("{name}.observation.txt")),format!("Genuine public-command state at tick {}.\n{s:#?}\n",s.world.tick)).unwrap();let mut r=SimHandle::from_lot();let loads=r.load_bytes(&bytes);let exact=loads&&r.save_bytes()==bytes;let hash=loads&&r.world_hash()==h.world_hash();let next=if exact{h.tick();r.tick();h.save_bytes()==r.save_bytes()}else{false};println!("capture\t{name}\t{}\t{}\t{loads}\t{exact}\t{hash}\t{next}",s.world.tick,bytes.len());assert!(loads&&exact&&hash&&next,"published continuation {name}");}
fn friends()->(SimHandle,u32,u32){let mut h=SimHandle::from_lot();let ps=people(&state(&h));let(a,b)=(ps[1],ps[2]);send(&mut h,SimCommand::SetChoreBoard{enabled:false});h.flush_commands();for _ in 0..3{send(&mut h,SimCommand::TalkToFirst{agent:a,target:b,interaction:0});h.flush_commands();for _ in 0..1440{h.tick();let s=state(&h);if feel(&s,a,b)>0.&&feel(&s,b,a)>0.&&s.world.entities.iter().filter(|e|e.index==a||e.index==b).all(|e|e.socialising.is_none()){println!("friends\t{}\t{a}\t{b}\t{}\t{}",s.world.tick,feel(&s,a,b),feel(&s,b,a));return(h,a,b);}}}panic!("No actual positive completed conversation within bound");}
fn is_media(s:&SaveSnapshotV5,p:u32,model:&str)->bool{s.world.entities.iter().find(|e|e.index==p).unwrap().eating.as_ref().is_some_and(|e|e.object==model&&e.remaining_ticks>0)}
fn meal(s:&SaveSnapshotV5,p:u32)->bool{s.world.entities.iter().find(|e|e.index==p).is_some_and(|e|e.path.is_none()&&e.step_work_ticks.is_some_and(|w|w>0)&&e.carrying.as_deref()==Some("dinner")&&e.chain.as_ref().is_some_and(|c|(c.chain=="cook_dinner"&&c.step==5)||(c.chain=="eat_shared_meal"&&c.step==1)))&&s.domestic.as_ref().is_some_and(|d|d.meals.iter().any(|m|m.dining_started))}
fn main(){let arg=std::env::args().nth(1).unwrap();let root=Path::new(&arg);fs::create_dir_all(root).unwrap();
 for (name,model) in [("two-viewer-tv","television"),("two-listener-radio","radio")]{let(mut h,a,b)=friends();let target=object(&state(&h),model);for p in[a,b]{send(&mut h,SimCommand::UseObjectFirst{agent:p,object:target,interaction:0});}h.flush_commands();let mut found=false;for _ in 0..1440{h.tick();let s=state(&h);if is_media(&s,a,model)&&is_media(&s,b,model){let ea=s.world.entities.iter().find(|e|e.index==a).unwrap();let eb=s.world.entities.iter().find(|e|e.index==b).unwrap();assert_ne!(ea.position,eb.position);assert!(feel(&s,a,b)>0.&&feel(&s,b,a)>0.);capture(root,name,&mut h);found=true;break;}}println!("observed\t{name}\t{found}");}
 for (name,remove_seats) in [("seated-company-meal",false),("standing-meal",true)]{let(mut h,a,b)=friends();let s=state(&h);if remove_seats{for chair in s.world.entities.iter().filter(|e|e.smart_object.as_deref()==Some("chair")){send(&mut h,SimCommand::SellObject{object:chair.index});}h.flush_commands();assert!(state(&h).world.entities.iter().all(|e|e.smart_object.as_deref()!=Some("chair")));}let fridge=object(&state(&h),"fridge");send(&mut h,SimCommand::UseObjectFirst{agent:a,object:fridge,interaction:1});h.flush_commands();let mut found=false;for _ in 0..2880{h.tick();let s=state(&h);let diners=s.dining.as_ref().map(|d|d.diners.as_slice()).unwrap_or(&[]);if meal(&s,a)&&meal(&s,b){let seat_a=diners.iter().find(|d|d.person==a).and_then(|d|d.chair);let seat_b=diners.iter().find(|d|d.person==b).and_then(|d|d.chair);let wanted=if remove_seats{seat_a.is_none()&&seat_b.is_none()}else{seat_a.is_some()&&seat_b.is_some()&&seat_a!=seat_b};if wanted{assert!(feel(&s,a,b)>0.&&feel(&s,b,a)>0.);capture(root,name,&mut h);found=true;break;}}}println!("observed\t{name}\t{found}");}
}
