// GENERATED by assets/sprites/build-atlas.ps1. Do not edit by hand.
//
// The renderer's half of the atlas manifest. The other half is
// assets/sprites/atlas.toml, which terri-data validates content
// against; `atlas.test.ts` reads that file and fails if the two drift.
//
// A sprite's INDEX is its position in `SPRITES`, and that index is what
// the render buffer carries for every entity. It has to agree with the
// order of the [[sprite]] blocks in the TOML, which is why both files
// are written in one pass rather than maintained separately.

/** One packed sprite. `w` and `h` are texels and screen pixels alike. */
export interface AtlasSprite {
  readonly name: string;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export const ATLAS_WIDTH = 512;
export const ATLAS_HEIGHT = 356;

export const SPRITES: readonly AtlasSprite[] = [
  { name: 'floor', x: 281, y: 267, w: 64, h: 42 },
  { name: 'sim', x: 159, y: 116, w: 38, h: 78 },
  { name: 'wallNS', x: 246, y: 1, w: 32, h: 98 },
  { name: 'wallEW', x: 213, y: 1, w: 32, h: 99 },
  { name: 'kitchenFridgeBuiltIn', x: 1, y: 116, w: 49, h: 83 },
  { name: 'bathroomSinkSquare', x: 199, y: 267, w: 41, h: 46 },
  { name: 'showerRound', x: 279, y: 1, w: 63, h: 94 },
  { name: 'toiletSquare', x: 78, y: 267, w: 36, h: 50 },
  { name: 'bookcaseClosedDoors', x: 296, y: 116, w: 36, h: 74 },
  { name: 'loungeSofaOttoman', x: 148, y: 267, w: 50, h: 47 },
  { name: 'televisionVintage', x: 411, y: 267, w: 34, h: 40 },
  { name: 'bedBunk', x: 1, y: 1, w: 93, h: 114 },
  { name: 'selectionRing', x: 346, y: 267, w: 64, h: 42 },
  { name: 'kitchenStove', x: 267, y: 200, w: 50, h: 59 },
  { name: 'kitchenCabinet', x: 318, y: 200, w: 50, h: 59 },
  { name: 'kitchenSink', x: 369, y: 200, w: 50, h: 59 },
  { name: 'table', x: 391, y: 116, w: 72, h: 70 },
  { name: 'chair', x: 257, y: 267, w: 23, h: 43 },
  { name: 'trashcan', x: 480, y: 267, w: 18, h: 35 },
  { name: 'loungeSofaLong', x: 198, y: 116, w: 97, h: 76 },
  { name: 'loungeChair', x: 420, y: 200, w: 49, h: 57 },
  { name: 'loungeChairRelax', x: 333, y: 116, w: 57, h: 72 },
  { name: 'radio', x: 29, y: 321, w: 22, h: 27 },
  { name: 'pottedPlant', x: 241, y: 267, w: 15, h: 46 },
  { name: 'cardboardBoxOpen', x: 446, y: 267, w: 33, h: 36 },
  { name: 'lampRoundFloor', x: 470, y: 200, w: 13, h: 57 },
  { name: 'coatRackStanding', x: 484, y: 200, w: 17, h: 54 },
  { name: 'bedDouble', x: 95, y: 1, w: 117, h: 103 },
  { name: 'sideTableDrawers', x: 35, y: 267, w: 42, h: 52 },
  { name: 'cabinetBedDrawer', x: 1, y: 321, w: 27, h: 34 },
  { name: 'desk', x: 1, y: 200, w: 63, h: 66 },
  { name: 'chairDesk', x: 1, y: 267, w: 33, h: 53 },
  { name: 'bookcaseClosedWide', x: 440, y: 1, w: 59, h: 87 },
  { name: 'bathtub', x: 343, y: 1, w: 96, h: 88 },
  { name: 'washerDryerStacked', x: 51, y: 116, w: 41, h: 82 },
  { name: 'wallCornerNW', x: 115, y: 267, w: 32, h: 49 },
  { name: 'doorwayNS', x: 93, y: 116, w: 32, h: 80 },
  { name: 'doorwayEW', x: 126, y: 116, w: 32, h: 79 },
  { name: 'kitchenStoveSW', x: 117, y: 200, w: 49, h: 60 },
  { name: 'kitchenCabinetSW', x: 167, y: 200, w: 49, h: 60 },
  { name: 'kitchenSinkSW', x: 217, y: 200, w: 49, h: 60 },
  { name: 'kitchenCabinetCornerInnerSW', x: 65, y: 200, w: 51, h: 62 },
  { name: 'indicatorTalk', x: 52, y: 321, w: 26, h: 26 },
  { name: 'indicatorEat', x: 79, y: 321, w: 26, h: 26 },
  { name: 'indicatorSleep', x: 106, y: 321, w: 26, h: 26 },
  { name: 'indicatorWait', x: 133, y: 321, w: 26, h: 26 },
  { name: 'carried_ingredients', x: 160, y: 321, w: 18, h: 18 },
  { name: 'carried_dinner', x: 179, y: 321, w: 18, h: 18 },
];

/**
 * The index of a sprite the shell itself draws - the floor and the two
 * wall orientations - by name.
 *
 * Smart objects must NOT come through here. Their sprite is content, so
 * it arrives already resolved in the render buffer; naming one here
 * would be a second copy of the object list in TypeScript.
 *
 * Throws rather than returning -1: an unknown name is a build mistake,
 * and -1 would index the uniform array out of range, which WGSL clamps
 * instead of trapping - so the whole floor would silently draw as some
 * other sprite.
 */
export function spriteIndex(name: string): number {
  const index = SPRITES.findIndex((sprite) => sprite.name === name);
  if (index < 0) {
    throw new Error(`atlas.png has no sprite named ${name}`);
  }
  return index;
}
