// GENERATED by assets/sprites/gen/build.py. Do not edit by hand.
//
// The renderer's half of the atlas manifest. The other half is
// assets/sprites/atlas.toml, which terri-data validates content
// against; `atlas.test.ts` reads that file and fails if the two drift.
//
// A sprite's INDEX is its position in `SPRITES`, and that index is what
// the render buffer carries for every entity. It has to agree with the
// order of the [[sprite]] blocks in the TOML, which is why both files
// are written in one pass rather than maintained separately.

/** One packed sprite. `w` and `h` are texels and screen pixels alike. */
export interface AtlasSprite {
  readonly name: string;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

export const ATLAS_WIDTH = 512;
export const ATLAS_HEIGHT = 1129;

export const SPRITES: readonly AtlasSprite[] = [
  { name: 'floor', x: 0, y: 1086, w: 64, h: 42 },
  { name: 'sim', x: 295, y: 133, w: 38, h: 88 },
  { name: 'wallNS', x: 204, y: 0, w: 32, h: 109 },
  { name: 'wallEW', x: 237, y: 0, w: 32, h: 109 },
  { name: 'kitchenFridgeBuiltIn', x: 400, y: 0, w: 54, h: 99 },
  { name: 'bathroomSinkSquare', x: 184, y: 1018, w: 32, h: 63 },
  { name: 'showerRound', x: 336, y: 0, w: 54, h: 102 },
  { name: 'toiletSquare', x: 53, y: 1018, w: 42, h: 66 },
  { name: 'bookcaseClosedDoors', x: 455, y: 0, w: 54, h: 99 },
  { name: 'loungeSofaOttoman', x: 268, y: 1018, w: 58, h: 58 },
  { name: 'televisionVintage', x: 96, y: 1018, w: 34, h: 65 },
  { name: 'bedBunk', x: 0, y: 0, w: 120, h: 132 },
  { name: 'selectionRing', x: 65, y: 1086, w: 64, h: 42 },
  { name: 'kitchenStove', x: 234, y: 852, w: 66, h: 76 },
  { name: 'kitchenCabinet', x: 301, y: 852, w: 66, h: 76 },
  { name: 'kitchenSink', x: 368, y: 852, w: 66, h: 76 },
  { name: 'table', x: 311, y: 941, w: 70, h: 69 },
  { name: 'chair', x: 435, y: 852, w: 48, h: 76 },
  { name: 'trashcan', x: 130, y: 1086, w: 16, h: 31 },
  { name: 'loungeSofaLong', x: 174, y: 133, w: 120, h: 92 },
  { name: 'loungeChair', x: 0, y: 1018, w: 52, h: 67 },
  { name: 'loungeChairRelax', x: 382, y: 941, w: 52, h: 69 },
  { name: 'radio', x: 401, y: 1018, w: 24, h: 51 },
  { name: 'pottedPlant', x: 426, y: 1018, w: 42, h: 43 },
  { name: 'cardboardBoxOpen', x: 217, y: 1018, w: 50, h: 60 },
  { name: 'lampRoundFloor', x: 327, y: 1018, w: 36, h: 55 },
  { name: 'coatRackStanding', x: 484, y: 852, w: 24, h: 76 },
  { name: 'bedDouble', x: 53, y: 133, w: 120, h: 94 },
  { name: 'sideTableDrawers', x: 131, y: 1018, w: 52, h: 64 },
  { name: 'cabinetBedDrawer', x: 364, y: 1018, w: 36, h: 54 },
  { name: 'desk', x: 435, y: 941, w: 70, h: 69 },
  { name: 'chairDesk', x: 268, y: 941, w: 42, h: 75 },
  { name: 'bookcaseClosedWide', x: 121, y: 0, w: 82, h: 119 },
  { name: 'bathtub', x: 117, y: 852, w: 116, h: 83 },
  { name: 'washerDryerStacked', x: 0, y: 133, w: 52, h: 95 },
  { name: 'wallCornerNW', x: 391, y: 0, w: 8, h: 101 },
  { name: 'doorwayNS', x: 270, y: 0, w: 32, h: 109 },
  { name: 'doorwayEW', x: 303, y: 0, w: 32, h: 109 },
  { name: 'kitchenStoveSW', x: 0, y: 941, w: 66, h: 76 },
  { name: 'kitchenCabinetSW', x: 67, y: 941, w: 66, h: 76 },
  { name: 'kitchenSinkSW', x: 134, y: 941, w: 66, h: 76 },
  { name: 'kitchenCabinetCornerInnerSW', x: 201, y: 941, w: 66, h: 76 },
  { name: 'indicatorTalk', x: 147, y: 1086, w: 26, h: 26 },
  { name: 'indicatorEat', x: 174, y: 1086, w: 26, h: 26 },
  { name: 'indicatorSleep', x: 201, y: 1086, w: 26, h: 26 },
  { name: 'indicatorWait', x: 228, y: 1086, w: 26, h: 26 },
  { name: 'carried_ingredients', x: 282, y: 1086, w: 16, h: 20 },
  { name: 'carried_dinner', x: 299, y: 1086, w: 18, h: 14 },
  { name: 'sim2', x: 334, y: 133, w: 38, h: 88 },
  { name: 'sim3', x: 373, y: 133, w: 38, h: 88 },
  { name: 'simTalkSE0', x: 412, y: 133, w: 38, h: 88 },
  { name: 'simTalkSE1', x: 451, y: 133, w: 38, h: 88 },
  { name: 'simTalkNW0', x: 0, y: 229, w: 38, h: 88 },
  { name: 'simTalkNW1', x: 39, y: 229, w: 38, h: 88 },
  { name: 'simTalkSW0', x: 78, y: 229, w: 38, h: 88 },
  { name: 'simTalkSW1', x: 117, y: 229, w: 38, h: 88 },
  { name: 'simTalkNE0', x: 156, y: 229, w: 38, h: 88 },
  { name: 'simTalkNE1', x: 195, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkSE0', x: 234, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkSE1', x: 273, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkNW0', x: 312, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkNW1', x: 351, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkSW0', x: 390, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkSW1', x: 429, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkNE0', x: 468, y: 229, w: 38, h: 88 },
  { name: 'sim2TalkNE1', x: 0, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkSE0', x: 39, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkSE1', x: 78, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkNW0', x: 117, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkNW1', x: 156, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkSW0', x: 195, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkSW1', x: 234, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkNE0', x: 273, y: 318, w: 38, h: 88 },
  { name: 'sim3TalkNE1', x: 312, y: 318, w: 38, h: 88 },
  { name: 'simEatSE0', x: 351, y: 318, w: 38, h: 88 },
  { name: 'simEatSE1', x: 390, y: 318, w: 38, h: 88 },
  { name: 'simEatNW0', x: 429, y: 318, w: 38, h: 88 },
  { name: 'simEatNW1', x: 468, y: 318, w: 38, h: 88 },
  { name: 'simEatSW0', x: 0, y: 407, w: 38, h: 88 },
  { name: 'simEatSW1', x: 39, y: 407, w: 38, h: 88 },
  { name: 'simEatNE0', x: 78, y: 407, w: 38, h: 88 },
  { name: 'simEatNE1', x: 117, y: 407, w: 38, h: 88 },
  { name: 'sim2EatSE0', x: 156, y: 407, w: 38, h: 88 },
  { name: 'sim2EatSE1', x: 195, y: 407, w: 38, h: 88 },
  { name: 'sim2EatNW0', x: 234, y: 407, w: 38, h: 88 },
  { name: 'sim2EatNW1', x: 273, y: 407, w: 38, h: 88 },
  { name: 'sim2EatSW0', x: 312, y: 407, w: 38, h: 88 },
  { name: 'sim2EatSW1', x: 351, y: 407, w: 38, h: 88 },
  { name: 'sim2EatNE0', x: 390, y: 407, w: 38, h: 88 },
  { name: 'sim2EatNE1', x: 429, y: 407, w: 38, h: 88 },
  { name: 'sim3EatSE0', x: 468, y: 407, w: 38, h: 88 },
  { name: 'sim3EatSE1', x: 0, y: 496, w: 38, h: 88 },
  { name: 'sim3EatNW0', x: 39, y: 496, w: 38, h: 88 },
  { name: 'sim3EatNW1', x: 78, y: 496, w: 38, h: 88 },
  { name: 'sim3EatSW0', x: 117, y: 496, w: 38, h: 88 },
  { name: 'sim3EatSW1', x: 156, y: 496, w: 38, h: 88 },
  { name: 'sim3EatNE0', x: 195, y: 496, w: 38, h: 88 },
  { name: 'sim3EatNE1', x: 234, y: 496, w: 38, h: 88 },
  { name: 'simReadSE0', x: 273, y: 496, w: 38, h: 88 },
  { name: 'simReadSE1', x: 312, y: 496, w: 38, h: 88 },
  { name: 'simReadNW0', x: 351, y: 496, w: 38, h: 88 },
  { name: 'simReadNW1', x: 390, y: 496, w: 38, h: 88 },
  { name: 'simReadSW0', x: 429, y: 496, w: 38, h: 88 },
  { name: 'simReadSW1', x: 468, y: 496, w: 38, h: 88 },
  { name: 'simReadNE0', x: 0, y: 585, w: 38, h: 88 },
  { name: 'simReadNE1', x: 39, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadSE0', x: 78, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadSE1', x: 117, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadNW0', x: 156, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadNW1', x: 195, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadSW0', x: 234, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadSW1', x: 273, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadNE0', x: 312, y: 585, w: 38, h: 88 },
  { name: 'sim2ReadNE1', x: 351, y: 585, w: 38, h: 88 },
  { name: 'sim3ReadSE0', x: 390, y: 585, w: 38, h: 88 },
  { name: 'sim3ReadSE1', x: 429, y: 585, w: 38, h: 88 },
  { name: 'sim3ReadNW0', x: 468, y: 585, w: 38, h: 88 },
  { name: 'sim3ReadNW1', x: 0, y: 674, w: 38, h: 88 },
  { name: 'sim3ReadSW0', x: 39, y: 674, w: 38, h: 88 },
  { name: 'sim3ReadSW1', x: 78, y: 674, w: 38, h: 88 },
  { name: 'sim3ReadNE0', x: 117, y: 674, w: 38, h: 88 },
  { name: 'sim3ReadNE1', x: 156, y: 674, w: 38, h: 88 },
  { name: 'indicatorReading', x: 255, y: 1086, w: 26, h: 26 },
  { name: 'simStandReadSE0', x: 195, y: 674, w: 38, h: 88 },
  { name: 'simStandReadSE1', x: 234, y: 674, w: 38, h: 88 },
  { name: 'simStandReadNW0', x: 273, y: 674, w: 38, h: 88 },
  { name: 'simStandReadNW1', x: 312, y: 674, w: 38, h: 88 },
  { name: 'simStandReadSW0', x: 351, y: 674, w: 38, h: 88 },
  { name: 'simStandReadSW1', x: 390, y: 674, w: 38, h: 88 },
  { name: 'simStandReadNE0', x: 429, y: 674, w: 38, h: 88 },
  { name: 'simStandReadNE1', x: 468, y: 674, w: 38, h: 88 },
  { name: 'sim2StandReadSE0', x: 0, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadSE1', x: 39, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadNW0', x: 78, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadNW1', x: 117, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadSW0', x: 156, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadSW1', x: 195, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadNE0', x: 234, y: 763, w: 38, h: 88 },
  { name: 'sim2StandReadNE1', x: 273, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadSE0', x: 312, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadSE1', x: 351, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadNW0', x: 390, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadNW1', x: 429, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadSW0', x: 468, y: 763, w: 38, h: 88 },
  { name: 'sim3StandReadSW1', x: 0, y: 852, w: 38, h: 88 },
  { name: 'sim3StandReadNE0', x: 39, y: 852, w: 38, h: 88 },
  { name: 'sim3StandReadNE1', x: 78, y: 852, w: 38, h: 88 },
];

/**
 * The index of a sprite the shell itself draws by name, including lot
 * geometry and presentation overlays such as rings and indicators.
 *
 * Smart-object render rows must NOT derive their sprite through here. Their
 * sprite is content, so it arrives already resolved in the render buffer.
 * Presentation profiles may resolve a named atlas slot, then compare it with
 * that resolved column; they must not infer an object's sprite from kind or id.
 *
 * Throws rather than returning -1: an unknown name is a build mistake,
 * and -1 would index the uniform array out of range, which WGSL clamps
 * instead of trapping - so the whole floor would silently draw as some
 * other sprite.
 */
export function spriteIndex(name: string): number {
  const index = SPRITES.findIndex((sprite) => sprite.name === name);
  if (index < 0) {
    throw new Error(`atlas.png has no sprite named ${name}`);
  }
  return index;
}
