// Generated by assets/sprites/gen/build.py; do not edit.
/** Content-addressed public pathname of every coverage table's bytes, gzip-compressed. */
export const COVERAGE_FILE_NAME = 'coverage-4056f61bfd516e9820558cb0d820d0a665a77a51eeca86fbca546b4a40605587.bin';
/** Length of the decompressed bytes. Coverage records hold offsets into them. */
export const COVERAGE_BYTE_LENGTH = 70060832;
