#!/usr/bin/env python3
"""Five ORIGINAL isometric art directions, drawn from scratch.

No Kenney. No pack. Every pixel here is generated by this file.

The bet: at a locked isometric camera and ~80 px per object, furniture is
shaded boxes. So one primitive renderer plus one object vocabulary plus a
STYLE (palette, outline, corner radius, shading model, character build)
gives a complete art direction, and five styles give five directions off
the same object list. That is [O2]/[O3] in TECH_STACK.md made real, and it
is also how the shipped game already draws its floor and its sim.
"""
import math, os
from PIL import Image, ImageDraw, ImageFilter

OUT = "/tmp/claude-0/-home-user-terrilives/1cad3393-2863-576b-9bf6-30e4a5e6b589/scratchpad/art"
os.makedirs(OUT, exist_ok=True)

HW, HH = 32, 21          # the game's real half-tile, from web/src/render/iso.ts
PX_PER_TILE_Z = 38       # how tall one "tile unit" of height draws

def sx(x, y): return (x - y) * HW
def sy(x, y): return (x + y) * HH

def mul(c, f):
    return tuple(max(0, min(255, int(v * f))) for v in c[:3]) + ((c[3],) if len(c) > 3 else ())

def mix(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


# --------------------------------------------------------------------------
# STYLE: the whole art direction, as data
# --------------------------------------------------------------------------
class Style:
    def __init__(self, key, name, pal, *, outline=None, outline_w=1, top=1.0,
                 right=0.80, left=0.60, radius=0, shadow=0.0, rim=None,
                 char=None, grain=0.0, edge_light=None, bg=None):
        self.key, self.name, self.pal = key, name, pal
        self.outline, self.outline_w = outline, outline_w
        self.top, self.right, self.left = top, right, left
        self.radius, self.shadow, self.rim = radius, shadow, rim
        self.char = char or {}
        self.grain, self.edge_light = grain, edge_light
        self.bg = bg or pal["bg"]

    def c(self, k):
        return self.pal[k]


# --------------------------------------------------------------------------
# ISO PRIMITIVES
# --------------------------------------------------------------------------
def box(d, st, ox, oy, x0, y0, x1, y1, z0, z1, colour, *, top_c=None, flat=False):
    """An axis-aligned box in tile space, drawn as its three visible faces."""
    zt, zb = z1 * PX_PER_TILE_Z, z0 * PX_PER_TILE_Z
    def P(x, y, z): return (ox + sx(x, y), oy + sy(x, y) - z)

    N, E, S, W = (x0, y0), (x1, y0), (x1, y1), (x0, y1)
    top = [P(*N, zt), P(*E, zt), P(*S, zt), P(*W, zt)]
    right = [P(*E, zt), P(*S, zt), P(*S, zb), P(*E, zb)]
    left = [P(*W, zt), P(*S, zt), P(*S, zb), P(*W, zb)]

    ol = st.outline
    w = st.outline_w
    tc = top_c or colour
    if flat:
        cl = cr = ct = colour
    else:
        ct = mul(tc, st.top)
        cr = mul(colour, st.right)
        cl = mul(colour, st.left)
    d.polygon(left, fill=cl, outline=ol, width=w)
    d.polygon(right, fill=cr, outline=ol, width=w)
    d.polygon(top, fill=ct, outline=ol, width=w)
    if st.edge_light:                      # a lit lip along the top edges
        d.line([top[3], top[0], top[1]], fill=st.edge_light, width=1)


def slab(d, st, ox, oy, x0, y0, x1, y1, z, colour, thick=0.06):
    box(d, st, ox, oy, x0, y0, x1, y1, z - thick, z, colour)


def cyl(d, st, ox, oy, cx, cy, r, z0, z1, colour):
    """Good enough for lamps, plants, mugs: an ellipse-topped column."""
    zt, zb = z1 * PX_PER_TILE_Z, z0 * PX_PER_TILE_Z
    px, py = ox + sx(cx, cy), oy + sy(cx, cy)
    rx, ry = r * HW * 1.3, r * HH * 1.3
    body = [(px - rx, py - zt), (px + rx, py - zt), (px + rx, py - zb), (px - rx, py - zb)]
    d.polygon(body, fill=mul(colour, st.right), outline=st.outline, width=st.outline_w)
    d.ellipse([px - rx, py - zb - ry, px + rx, py - zb + ry], fill=mul(colour, st.right),
              outline=st.outline, width=st.outline_w)
    d.ellipse([px - rx, py - zt - ry, px + rx, py - zt + ry], fill=mul(colour, st.top),
              outline=st.outline, width=st.outline_w)


# --------------------------------------------------------------------------
# THE OBJECT VOCABULARY - one definition, five looks
# --------------------------------------------------------------------------
def o_floor(d, st, ox, oy, x, y):
    a, b = st.c("floor"), st.c("floor2")
    col = a if (x + y) % 2 == 0 else b
    pts = [(ox + sx(x, y), oy + sy(x, y)),
           (ox + sx(x + 1, y), oy + sy(x + 1, y)),
           (ox + sx(x + 1, y + 1), oy + sy(x + 1, y + 1)),
           (ox + sx(x, y + 1), oy + sy(x, y + 1))]
    d.polygon(pts, fill=col, outline=st.c("grout"), width=1)


def o_wall(d, st, ox, oy, x, y, axis, length=1, height=1.75):
    """A wall on a tile EDGE, drawn as ONE box for the whole RUN.

    Two things the shipped renderer does not do, and both are why its
    walls read as a picket fence. It puts a half-tile-wide panel at the
    tile CENTRE (tiles.ts says so: "a 32 px panel on a 64 px tile already
    leaves floor showing beside every wall"), and it emits one instance
    per tile, so any per-panel edge repeats every 32 px and the run
    stripes. On the edge and in one piece, a run is a surface. This is
    [B7].
    """
    t = 0.14
    c = st.c("wall")
    if axis == "ew":
        box(d, st, ox, oy, x, y, x + length, y + t, 0, height, c, top_c=st.c("wall_top"))
        if st.c("skirt"):
            box(d, st, ox, oy, x, y, x + length, y + t + .02, 0, .14, st.c("skirt"))
    else:
        box(d, st, ox, oy, x, y, x + t, y + length, 0, height, c, top_c=st.c("wall_top"))
        if st.c("skirt"):
            box(d, st, ox, oy, x, y, x + t + .02, y + length, 0, .14, st.c("skirt"))


def o_rug(d, st, ox, oy, x, y, w=2, h=2):
    col = st.pal["accents"][1]
    pts = [(ox + sx(x, y), oy + sy(x, y)),
           (ox + sx(x + w, y), oy + sy(x + w, y)),
           (ox + sx(x + w, y + h), oy + sy(x + w, y + h)),
           (ox + sx(x, y + h), oy + sy(x, y + h))]
    d.polygon(pts, fill=col, outline=st.outline, width=st.outline_w)
    inner = [(ox + sx(x + .22, y + .22), oy + sy(x + .22, y + .22)),
             (ox + sx(x + w - .22, y + .22), oy + sy(x + w - .22, y + .22)),
             (ox + sx(x + w - .22, y + h - .22), oy + sy(x + w - .22, y + h - .22)),
             (ox + sx(x + .22, y + h - .22), oy + sy(x + .22, y + h - .22))]
    d.polygon(inner, fill=mul(col, 1.14), outline=st.outline, width=st.outline_w)


def o_bed(d, st, ox, oy, x, y):
    w = st.c("wood")
    box(d, st, ox, oy, x + .05, y + .05, x + .95, y + 1.95, 0, .28, w)          # base
    box(d, st, ox, oy, x + .05, y + .05, x + .95, y + .18, 0, .78, w)           # headboard
    slab(d, st, ox, oy, x + .08, y + .2, x + .92, y + 1.92, .46, st.c("linen"), thick=.18)
    slab(d, st, ox, oy, x + .08, y + .95, x + .92, y + 1.92, .5, st.c("fabric"), thick=.12)
    slab(d, st, ox, oy, x + .15, y + .26, x + .85, y + .62, .52, st.c("linen2"), thick=.1)


def o_table(d, st, ox, oy, x, y):
    w = st.c("wood")
    for dx, dy in ((.1, .1), (.82, .1), (.1, .82), (.82, .82)):
        box(d, st, ox, oy, x + dx, y + dy, x + dx + .08, y + dy + .08, 0, .52, mul(w, .85))
    slab(d, st, ox, oy, x + .02, y + .02, x + .98, y + .98, .62, w, thick=.1)


def o_chair(d, st, ox, oy, x, y):
    w = st.c("wood2")
    for dx, dy in ((.24, .24), (.64, .24), (.24, .64), (.64, .64)):
        box(d, st, ox, oy, x + dx, y + dy, x + dx + .07, y + dy + .07, 0, .38, mul(w, .85))
    slab(d, st, ox, oy, x + .2, y + .2, x + .8, y + .8, .46, w, thick=.08)
    box(d, st, ox, oy, x + .2, y + .2, x + .8, y + .29, .46, .95, w)


def o_sofa(d, st, ox, oy, x, y):
    f = st.c("fabric")
    box(d, st, ox, oy, x + .05, y + .05, x + 1.95, y + .95, 0, .34, mul(f, .9))
    slab(d, st, ox, oy, x + .08, y + .3, x + 1.92, y + .92, .5, f, thick=.16)
    box(d, st, ox, oy, x + .05, y + .05, x + 1.95, y + .3, 0, .82, f)            # back
    box(d, st, ox, oy, x + .05, y + .05, x + .22, y + .95, 0, .62, mul(f, .95))  # arms
    box(d, st, ox, oy, x + 1.78, y + .05, x + 1.95, y + .95, 0, .62, mul(f, .95))


def o_counter(d, st, ox, oy, x, y, kind="plain"):
    box(d, st, ox, oy, x + .04, y + .04, x + .96, y + .96, 0, .78, st.c("cab"))
    slab(d, st, ox, oy, x, y, x + 1, y + 1, .86, st.c("counter"), thick=.08)
    if kind == "sink":
        d.polygon([(ox + sx(x + .3, y + .3), oy + sy(x + .3, y + .3) - .86 * PX_PER_TILE_Z),
                   (ox + sx(x + .78, y + .3), oy + sy(x + .78, y + .3) - .86 * PX_PER_TILE_Z),
                   (ox + sx(x + .78, y + .78), oy + sy(x + .78, y + .78) - .86 * PX_PER_TILE_Z),
                   (ox + sx(x + .3, y + .78), oy + sy(x + .3, y + .78) - .86 * PX_PER_TILE_Z)],
                  fill=mul(st.c("metal"), .8), outline=st.outline, width=st.outline_w)
    if kind == "hob":
        for cx, cy in ((.32, .32), (.68, .32), (.32, .68), (.68, .68)):
            p = (ox + sx(x + cx, y + cy), oy + sy(x + cx, y + cy) - .87 * PX_PER_TILE_Z)
            d.ellipse([p[0] - 7, p[1] - 5, p[0] + 7, p[1] + 5], fill=st.c("dark"),
                      outline=st.outline, width=st.outline_w)


def o_fridge(d, st, ox, oy, x, y):
    box(d, st, ox, oy, x + .06, y + .06, x + .94, y + .94, 0, 1.5, st.c("metal"))
    p0 = (ox + sx(x + .94, y + .3), oy + sy(x + .94, y + .3) - 1.0 * PX_PER_TILE_Z)
    d.line([p0, (p0[0], p0[1] + 16)], fill=st.c("dark"), width=3)


def o_bookcase(d, st, ox, oy, x, y):
    w = st.c("wood")
    box(d, st, ox, oy, x + .06, y + .06, x + .94, y + .5, 0, 1.5, mul(w, .8))
    for i in range(4):
        slab(d, st, ox, oy, x + .1, y + .1, x + .9, y + .46, .32 + i * .34, w, thick=.05)
        for j in range(4):                             # books, seeded by position
            bx = x + .14 + j * .18
            hgt = .18 + ((i * 7 + j * 3 + x + y) % 4) * .035
            col = st.pal["accents"][(i * 3 + j + int(x)) % len(st.pal["accents"])]
            box(d, st, ox, oy, bx, y + .16, bx + .13, y + .4, .37 + i * .34, .37 + i * .34 + hgt, col)


def o_tv(d, st, ox, oy, x, y):
    box(d, st, ox, oy, x + .3, y + .35, x + .7, y + .65, 0, .3, st.c("dark"))
    box(d, st, ox, oy, x + .1, y + .38, x + .9, y + .5, .3, .9, st.c("dark"))
    d.polygon([(ox + sx(x + .13, y + .4), oy + sy(x + .13, y + .4) - .86 * PX_PER_TILE_Z),
               (ox + sx(x + .87, y + .4), oy + sy(x + .87, y + .4) - .86 * PX_PER_TILE_Z),
               (ox + sx(x + .87, y + .4), oy + sy(x + .87, y + .4) - .36 * PX_PER_TILE_Z),
               (ox + sx(x + .13, y + .4), oy + sy(x + .13, y + .4) - .36 * PX_PER_TILE_Z)],
              fill=st.c("screen"), outline=st.outline, width=st.outline_w)


def o_toilet(d, st, ox, oy, x, y):
    p = st.c("porcelain")
    box(d, st, ox, oy, x + .3, y + .18, x + .7, y + .38, 0, .78, p)
    box(d, st, ox, oy, x + .28, y + .38, x + .72, y + .8, 0, .4, p)
    slab(d, st, ox, oy, x + .26, y + .36, x + .74, y + .82, .46, mul(p, .96), thick=.05)


def o_bath(d, st, ox, oy, x, y):
    p = st.c("porcelain")
    box(d, st, ox, oy, x + .06, y + .12, x + 1.9, y + .88, 0, .46, p)
    z = .46 * PX_PER_TILE_Z
    d.polygon([(ox + sx(x + .18, y + .24), oy + sy(x + .18, y + .24) - z),
               (ox + sx(x + 1.78, y + .24), oy + sy(x + 1.78, y + .24) - z),
               (ox + sx(x + 1.78, y + .76), oy + sy(x + 1.78, y + .76) - z),
               (ox + sx(x + .18, y + .76), oy + sy(x + .18, y + .76) - z)],
              fill=st.c("water"), outline=st.outline, width=st.outline_w)


def o_shower(d, st, ox, oy, x, y):
    p, g = st.c("porcelain"), st.c("water")
    box(d, st, ox, oy, x + .1, y + .1, x + .9, y + .9, 0, .14, p)
    box(d, st, ox, oy, x + .1, y + .1, x + .9, y + .18, .14, 1.55, mix(g, (255, 255, 255), .45))
    box(d, st, ox, oy, x + .1, y + .1, x + .18, y + .9, .14, 1.55, mix(g, (255, 255, 255), .3))


def o_plant(d, st, ox, oy, x, y):
    cyl(d, st, ox, oy, x + .5, y + .5, .18, 0, .34, st.c("pot"))
    g = st.c("leaf")
    px, py = ox + sx(x + .5, y + .5), oy + sy(x + .5, y + .5) - .34 * PX_PER_TILE_Z
    for a, ln in ((-70, 30), (-40, 40), (-10, 34), (25, 38), (55, 28), (95, 24)):
        r = math.radians(a - 90)
        d.line([(px, py), (px + math.cos(r) * ln * .8, py + math.sin(r) * ln)],
               fill=g, width=4 if st.outline is None else 5)
    d.ellipse([px - 4, py - 4, px + 4, py + 4], fill=mul(g, .9))


def o_lamp(d, st, ox, oy, x, y):
    px, py = ox + sx(x + .5, y + .5), oy + sy(x + .5, y + .5)
    ol, w = st.outline, st.outline_w
    d.ellipse([px - 13, py - 5, px + 13, py + 5], fill=mul(st.c("metal"), .8),
              outline=ol, width=w)                                    # base
    d.rectangle([px - 2, py - 1.28 * PX_PER_TILE_Z, px + 2, py], fill=st.c("metal"),
                outline=ol, width=w)                                  # stem
    sh, top = st.c("shade"), py - 1.28 * PX_PER_TILE_Z                # conical shade
    d.polygon([(px - 12, top + 20), (px - 19, top + 20), (px - 13, top - 4),
               (px + 13, top - 4), (px + 19, top + 20), (px + 12, top + 20)],
              fill=sh, outline=ol, width=w)
    d.ellipse([px - 19, top + 15, px + 19, top + 25], fill=mul(sh, 1.15),
              outline=ol, width=w)
    if st.key == "nightshift":                                        # it is a light
        glow = Image.new("RGBA", (140, 140), (0, 0, 0, 0))
        ImageDraw.Draw(glow).ellipse([10, 10, 130, 130], fill=(255, 196, 120, 46))
        return ("glow", glow.filter(ImageFilter.GaussianBlur(14)), (int(px - 70), int(py - 118)))


# --------------------------------------------------------------------------
# CHARACTERS - the thing the player actually looks at
# --------------------------------------------------------------------------
def sim(d, st, ox, oy, x, y, skin, hair, shirt, trouser, *, facing=1):
    """Drawn to the style's build: head ratio, shoulder width, stance."""
    ch = st.char
    H = ch.get("h", 86)
    head_r = H * ch.get("head", .21)
    px, py = ox + sx(x, y), oy + sy(x, y)
    ol, w = st.outline, st.outline_w
    sh = ch.get("shoulder", .34) * H
    hip = ch.get("hip", .26) * H
    leg = ch.get("leg", .38) * H
    torso = H - leg - head_r * 2
    slump = ch.get("slump", 0)

    if st.shadow:                                  # contact shadow
        d.ellipse([px - 14, py - 6, px + 14, py + 6],
                  fill=(0, 0, 0, int(150 * st.shadow)))

    ty = py - leg                                  # top of legs
    lw = hip * .42
    for s in (-1, 1):                              # legs
        cx = px + s * hip * .26
        d.rounded_rectangle([cx - lw / 2, ty, cx + lw / 2, py], radius=st.radius,
                            fill=trouser, outline=ol, width=w)
    # torso: a tapered body, wider at the shoulder
    top_y = ty - torso + slump
    body = [(px - sh / 2, top_y + torso * .18), (px - hip / 2, ty),
            (px + hip / 2, ty), (px + sh / 2, top_y + torso * .18)]
    if ch.get("bean"):
        d.rounded_rectangle([px - sh / 2, top_y, px + sh / 2, ty],
                            radius=int(sh * .48), fill=shirt, outline=ol, width=w)
    else:
        d.polygon(body + [(px + sh / 2, top_y), (px - sh / 2, top_y)],
                  fill=shirt, outline=ol, width=w)
    aw = sh * .22                                  # arms
    for s in (-1, 1):
        ax = px + s * (sh / 2 - aw * .3)
        d.rounded_rectangle([ax - aw / 2, top_y + torso * .1, ax + aw / 2, ty + leg * .12],
                            radius=st.radius or int(aw * .5), fill=mul(shirt, .92),
                            outline=ol, width=w)
    hy = top_y - head_r + slump                    # head
    if ch.get("square_head"):
        d.rounded_rectangle([px - head_r, hy - head_r, px + head_r, hy + head_r],
                            radius=int(head_r * .42), fill=skin, outline=ol, width=w)
    else:
        d.ellipse([px - head_r, hy - head_r, px + head_r, hy + head_r],
                  fill=skin, outline=ol, width=w)
    d.chord([px - head_r, hy - head_r, px + head_r, hy + head_r * .3],
            180, 360, fill=hair, outline=ol, width=w)          # hair cap
    ey = hy + head_r * .1                                       # eyes: one dot each
    r = max(1.2, head_r * .1)
    for s in (-1, 1):
        cx = px + s * head_r * .34 + facing * head_r * .06
        d.ellipse([cx - r, ey - r, cx + r, ey + r], fill=st.c("dark"))


# --------------------------------------------------------------------------
# THE FIVE DIRECTIONS
# --------------------------------------------------------------------------
STYLES = [
Style("municipal", "Municipal Beige",
  dict(bg=(38, 40, 42), floor=(178, 172, 150), floor2=(172, 166, 144), grout=(150, 144, 124),
       wall=(214, 209, 192), wall_top=(226, 221, 205), skirt=(140, 132, 112),
       wood=(150, 128, 92), wood2=(158, 136, 100), fabric=(122, 132, 118),
       linen=(206, 202, 188), linen2=(214, 210, 198), cab=(186, 178, 156),
       counter=(120, 116, 104), metal=(166, 170, 168), dark=(58, 56, 52),
       porcelain=(226, 226, 220), water=(168, 186, 186), screen=(76, 82, 78),
       pot=(150, 116, 92), leaf=(112, 132, 96), shade=(206, 196, 168),
       accents=[(140, 120, 96), (120, 128, 112), (154, 138, 108), (108, 112, 116)]),
  top=1.06, right=.86, left=.68, shadow=.35,
  char=dict(h=84, head=.155, shoulder=.30, hip=.24, leg=.42, slump=3)),

Style("bold", "Bold Flat",
  dict(bg=(26, 26, 46), floor=(255, 246, 227), floor2=(247, 236, 214), grout=(26, 26, 46),
       wall=(255, 210, 63), wall_top=(255, 226, 120), skirt=None,
       wood=(255, 107, 74), wood2=(255, 138, 92), fabric=(46, 196, 182),
       linen=(255, 255, 255), linen2=(255, 226, 120), cab=(74, 88, 153),
       counter=(255, 255, 255), metal=(160, 176, 208), dark=(26, 26, 46),
       porcelain=(255, 255, 255), water=(46, 196, 182), screen=(46, 196, 182),
       pot=(255, 107, 74), leaf=(64, 168, 108), shade=(255, 210, 63),
       accents=[(255, 107, 74), (46, 196, 182), (74, 88, 153), (255, 210, 63)]),
  outline=(26, 26, 46), outline_w=2, top=1.0, right=.88, left=.74, shadow=.16,
  char=dict(h=88, head=.25, shoulder=.36, hip=.28, leg=.30, square_head=True)),

Style("clay", "Soft Clay",
  dict(bg=(244, 236, 226), floor=(232, 216, 198), floor2=(226, 209, 190), grout=(212, 194, 176),
       wall=(246, 232, 216), wall_top=(252, 242, 230), skirt=(232, 214, 196),
       wood=(212, 168, 132), wood2=(220, 180, 146), fabric=(168, 208, 192),
       linen=(252, 248, 242), linen2=(242, 200, 190), cab=(226, 206, 226),
       counter=(248, 240, 230), metal=(206, 210, 216), dark=(92, 78, 74),
       porcelain=(252, 250, 246), water=(186, 216, 224), screen=(150, 146, 160),
       pot=(226, 158, 132), leaf=(140, 190, 150), shade=(248, 226, 176),
       accents=[(242, 181, 167), (168, 208, 192), (184, 169, 217), (248, 226, 176)]),
  top=1.05, right=.93, left=.85, radius=6, shadow=.10,
  char=dict(h=80, head=.27, shoulder=.32, hip=.30, leg=.26, bean=True)),

Style("nightshift", "Night Shift",
  dict(bg=(16, 18, 30), floor=(48, 52, 72), floor2=(44, 48, 66), grout=(34, 38, 54),
       wall=(38, 42, 60), wall_top=(56, 62, 84), skirt=(28, 31, 46),
       wood=(96, 74, 62), wood2=(104, 82, 68), fabric=(72, 68, 110),
       linen=(150, 158, 186), linen2=(120, 128, 160), cab=(52, 58, 78),
       counter=(70, 78, 100), metal=(96, 106, 130), dark=(12, 13, 22),
       porcelain=(130, 140, 164), water=(70, 110, 140), screen=(126, 196, 224),
       pot=(88, 66, 58), leaf=(64, 104, 84), shade=(255, 200, 130),
       accents=[(226, 138, 92), (110, 168, 216), (208, 96, 108), (240, 196, 120)]),
  top=1.22, right=.82, left=.55, shadow=.5, edge_light=(120, 140, 180),
  char=dict(h=86, head=.18, shoulder=.31, hip=.25, leg=.40)),

Style("papercut", "Paper Cut",
  dict(bg=(232, 224, 206), floor=(214, 198, 172), floor2=(206, 189, 163), grout=(186, 170, 146),
       wall=(233, 220, 192), wall_top=(246, 238, 218), skirt=(196, 178, 152),
       wood=(196, 138, 92), wood2=(206, 150, 104), fabric=(196, 90, 82),
       linen=(246, 240, 226), linen2=(226, 214, 190), cab=(124, 148, 152),
       counter=(238, 230, 212), metal=(168, 176, 176), dark=(61, 59, 58),
       porcelain=(244, 240, 230), water=(124, 168, 176), screen=(90, 106, 110),
       pot=(178, 104, 76), leaf=(122, 152, 96), shade=(232, 200, 132),
       accents=[(196, 90, 82), (94, 122, 140), (122, 152, 96), (216, 168, 88)]),
  top=1.12, right=.90, left=.80, shadow=.22, grain=.5, edge_light=(252, 248, 236),
  char=dict(h=84, head=.22, shoulder=.34, hip=.26, leg=.34)),
]


# --------------------------------------------------------------------------
# THE SCENE - a flat, drawn back to front
# --------------------------------------------------------------------------
W, H = 9, 7
PEOPLE = [
    (2.7, 1.1, "skin_a", 0),     # kitchen, at the hob
    (6.6, 2.5, "skin_b", 1),     # bedroom
    (2.6, 4.6, "skin_c", 2),     # living, on the rug
]
SKINS = [(232, 190, 156), (156, 112, 84), (198, 152, 118)]
HAIRS = [(58, 44, 38), (28, 26, 30), (128, 92, 54)]

def scene(st):
    pad_x, pad_y = 40, 150
    ow = (W + H) * HW + pad_x * 2
    oh = (W + H) * HH + pad_y + 120
    img = Image.new("RGB", (ow, oh), st.bg)
    d = ImageDraw.Draw(img, "RGBA")
    ox, oy = pad_x + H * HW, pad_y

    for y in range(H):
        for x in range(W):
            o_floor(d, st, ox, oy, x, y)
    o_rug(d, st, ox, oy, 0.7, 4.5, 2.6, 2.1)

    # Depth order: everything keyed on the far corner of its footprint.
    items = []
    def add(x, y, fn, *a): items.append((x + y, len(items), x, y, fn, a))

    # Boundary, as two runs rather than 16 panels.
    add(0, -0.14, o_wall, "ew", W)
    add(-0.14, 0, o_wall, "ns", H)
    # Interior walls. Each run stops short of the next: the gap IS the door.
    add(4.5, -0.14, o_wall, "ns", 2.5)          # kitchen | bedroom
    add(4.5, 3.4, o_wall, "ns", 3.7)            # living  | bathroom
    add(4.5, 3.5, o_wall, "ew", 2.6)            # bedroom | bathroom
    add(8.2, 3.5, o_wall, "ew", 0.9)

    # Kitchen, north-west
    add(0, 0, o_counter, "plain"); add(1, 0, o_counter, "sink"); add(2, 0, o_counter, "hob")
    add(3, 0, o_fridge)
    add(1.1, 2.0, o_table); add(1.1, 3.1, o_chair); add(0.1, 2.0, o_chair)
    # Living, south-west
    add(1.0, 5.0, o_sofa); add(3.3, 5.6, o_tv); add(0.1, 4.2, o_lamp)
    # Bedroom, north-east
    add(6.0, 0.1, o_bed); add(8.0, 0.2, o_bookcase); add(8.1, 2.4, o_plant)
    # Bathroom, south-east
    add(5.2, 5.6, o_bath); add(7.7, 4.4, o_toilet); add(8.0, 5.8, o_shower)
    add(3.6, 4.2, o_plant)

    for i, (x, y, _, _) in enumerate(PEOPLE):
        items.append((x + y + .4, 900 + i, x, y, "sim", (i,)))

    glows = []
    for _, _, x, y, fn, a in sorted(items, key=lambda t: (t[0], t[1])):
        if fn == "sim":
            i = a[0]
            sim(d, st, ox, oy, x, y, SKINS[i], HAIRS[i],
                st.pal["accents"][i % len(st.pal["accents"])],
                mul(st.c("dark"), 1.9 if st.key != "bold" else 2.4))
        else:
            r = fn(d, st, ox, oy, x, y, *a)
            if isinstance(r, tuple) and r[0] == "glow":
                glows.append(r[1:])
    for g, pos in glows:
        img.paste(Image.alpha_composite(
            img.crop((pos[0], pos[1], pos[0] + g.width, pos[1] + g.height)).convert("RGBA"), g
        ).convert("RGB"), pos)

    if st.grain:
        import random
        random.seed(3)
        g = Image.new("L", img.size)
        gp = g.load()
        for yy in range(img.height):
            for xx in range(img.width):
                gp[xx, yy] = 236 + random.randint(0, 19)
        img = Image.composite(img, Image.new("RGB", img.size, (0, 0, 0)), g.point(lambda v: v))
        img = Image.blend(img, Image.new("RGB", img.size, st.bg), 0.0)
        from PIL import ImageChops
        img = ImageChops.multiply(img, Image.merge("RGB", (g, g, g)))
    return img


for st in STYLES:
    im = scene(st)
    p = f"{OUT}/{st.key}.png"
    im.save(p, optimize=True)
    print(f"{st.key:12s} {st.name:18s} {im.size}  {os.path.getsize(p)//1024} KB")
